/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExperimentChooser: typeof import('./src/components/experiment-chooser.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HeaderAppBar: typeof import('./src/components/header-app-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Videoplayer: typeof import('./src/components/videoplayer.vue')['default']
  }
}
